# Generated by Django 5.1.6 on 2025-02-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], default='Unknown', max_length=10)),
                ('skin_color', models.CharField(choices=[('Fair', 'Fair'), ('Medium', 'Medium'), ('Dark', 'Dark'), ('Unknown', 'Unknown')], default='Unknown', max_length=10)),
                ('eye_color', models.CharField(choices=[('Brown', 'Brown'), ('Blue', 'Blue'), ('Green', 'Green'), ('Unknown', 'Unknown')], default='Unknown', max_length=10)),
                ('beard', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], default='Unknown', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
